### ISSUE TITLE
Multiple choices question

### ISSUE THREAD

**Issue by SanAlexis** [nyx-ei/pollingus#12]
# Story
As a poll operator, I want to conduct a polling where I ask a question with multiple choices.
As a poll applicant, I want to answer a multiple choices question on my WhatsApp account.
## Question notice
Automatically a notice is added at the end of the question to declare that there could be many possible choices.
## Kind of responses
The poll applicant could respond with a list of numbers specifying the choice position.
>
> ## Use case
> Q: What is the colour of the sky ?
> ⚠️ _many answers could fit_
> * blue
> * red
> * white
> * black
> 
> Possible answers:
> * 1,2 --> blue and red
> * 2,3 --> red and white
> * 3 --> white
> * 4 --> black

**Comment by Pattykev** [comment]
Complexity: 👍👍👍
Duration in days:👍👍👍

**Comment by yvankamdem** [comment]
c'est un 5 et peut être livrer sur 10 jours

**Comment by yvankamdem** [comment]
complexité : 5
durée ne jours : 9

**Comment by Pattykev** [comment]
Complexity: 5
Duration in days: 6

**Comment by Laetijo** [comment]
Complexity: 5
Duration in days: 6
